### ISSUE TITLE
Tinker Stages not updating for other players in lan world (visual only) 

### ISSUE THREAD

**Issue by mxnmnm** [Darkhax-Minecraft/TinkerStages#10]
It works yet it doesn't. I can pull out items like normal but the gui doesn't update to say that I have access to make the item. It doesn't even show the item in the output slot but you can still pull it out.

**Comment by Darkhax** [comment]
Which versions of the mods are you using? This sounds like a bug in GameStages that has already been fixed.

**Comment by mxnmnm** [comment]
I used gamestages 1.12.2-2.0.105 (the one you linked in the previous issue) and tinker's stages 1.12.2-2.0.15 if you need the versions for the other stuff I was using let me know

**Comment by Darkhax** [comment]
This issue should be fixed when using the latest versions of Tinkers Stages and GameStages. If it's not, let me know and I can do some deeper digging.
