### ISSUE TITLE
Suggestion: Tinker's Tool Leveling

### ISSUE THREAD

**Issue by UnlimatedStone9** [Darkhax-Minecraft/TinkerStages#12]
Alright so Tinker's Tool Levelling is a mod that, well, levels your Tinkers tools from using them, is it possible to have this stage-able when the mod is installed with this and Game-stages? Eg: when player is granted the chosen stage tools can now be levelled but if the player does not have the desired stage the tools cannot level yet, thanks!          -UnlimatedStone9

**Comment by Darkhax** [comment]
This may be possible, it fully depends on what that mod has for an API. I will look into this and give an update when I have more info.

**Comment by Darkhax** [comment]
This doesn't look possible with the existing versions. I am also in the process to moving to 1.16.5 so things will need to be reevaluated again once they update.
