### ISSUE TITLE
Can't open Compact Machines Personal Shrinking Device (manual), enter Compact Machines dimension or open Immersive Engineering Manual

### ISSUE THREAD

**Issue by PhoenixMage** [Darkhax-Minecraft/TinkerStages#13]
Running Modern Skyblock 3 Departed Modpack 3.5

**Description of the problem including expected versus actual behavior:**
When rightclicking the PSD anywhere, no manual shows.
When rightclicking the PSD onto a machine block, two dimension travels happen, one to go in, the next instantly to go out.
When rightclicking the Engineer's Manual anywhere, no manual shows.
All these behaviours don't happen in Creative mode (/gamemode 1)
Opping player has no effect.

**Steps to reproduce:**
Install the Modern Skyblock 3 pack locally (allocate at least 6GB of ram...).
Download and run the Modern Skyblock 3 server locally (allocate at least 3GB of ram...)
Log into server, run commands (op yourself on server):
/island create 1
/give yourname dirt 1
/give yourname sapling 1
Rightclick quest book (should be in inventory), select "Kitchensink Mode" and claim the quest reward (this unlocks everything)
/give yourname compactmachines3:psd
/give yourname compactmachines3:machine
Go into machine using PSD.
Observe a loading screen and then appearing right back in dimension 0.
/give yourname immersiveengineering:tool 1 3
Right click while holding manual and nothing occurs.

This does not happen if using creative mod on the server or if TinkerStage is removed.
MSB3 is running TinkerStages-1.12.2-2.0.15.jar

**Comment by Darkhax** [comment]
Does this pack also have Dimension Stages installed? If so, try removing it and let me know if that also fixes this issue.

**Comment by PhoenixMage** [comment]
Hi, yes it appears removing Dimension Stages also fixes the issue.

**Comment by Darkhax** [comment]
Okay, this issue is not TinkerStages. Removing TinkerStages breaks the script in the pack, preventing DimensionStages from running. That is the mod causing the issue. I don't really know how modern skyblock works, but dimension stages is designed to restrict players from going to the dimension until they have unlocked it. I am thinking the pack has a bug where they are not removing their restriction to this dimension.

**Comment by PhoenixMage** [comment]
Why would it work in a single player and not on a server then? Is there a log file that tells you what the errors are?
