### ISSUE TITLE
Suggestion: More Nuanced Tool Progression

### ISSUE THREAD

**Issue by mxnmnm** [Darkhax-Minecraft/TinkerStages#15]
Let's say you want to restrict iron shovel heads to a certain stage without impacting all shovel heads or all tools made out of iron.  I haven't seen anything like that on the wiki or curseforge page so I'm pretty sure you currently can't do that.  Would it be possible to add that in?  Thanks!

**Comment by Darkhax** [comment]
This is a good idea, however I am limited by what the Tinkers Construct mod provides access to.
