### ISSUE TITLE
Tinker Stages not updating for other players in lan world (visual only)

### ISSUE THREAD

**Issue by mxnmnm** [Darkhax-Minecraft/TinkerStages#6]
My friend can't craft stone tools or use anything related to tinkers stages progression even though we finished the quest that unlocks the stone stage.  Tested on my modpack "Crystal Progressions" in case you want to have a closer look at the environment the bug occurs.

**Comment by Darkhax** [comment]
Ask your friend to run `/gamestage info` and check if they have the stage. Stages are player based.

**Comment by mxnmnm** [comment]
They should have it because other items from that stage are unlocked.  And my friend did the command and he has that stage.

**Comment by mxnmnm** [comment]
Going to an older version seems to have fixed it, but it forces me to backport several other mods (mainly carry on) so a fix would be nice.

**Comment by Darkhax** [comment]
Using the [latest build](https://minecraft.curseforge.com/projects/game-stages/files/2610621) of GameStages should fix this error. Let me know if it works.

**Comment by mxnmnm** [comment]
It works yet it doesn't.  I can pull out items like normal but the gui doesn't update to say that I have access to make the item.  It doesn't even show the item in the output slot but you can still pull it out.
