### ISSUE TITLE
[1.12] Material Stage Glitch in the Part Crafter

### ISSUE THREAD

**Issue by MasterEnderman** [Darkhax-Minecraft/TinkerStages#9]
![image](https://user-images.githubusercontent.com/24524662/44403988-156c7500-a556-11e8-9064-c19c76d7d8ed.png)
 I have the required stage unlocked, but it still shows I'm unable to craft it. If I click in the crafting window, it'll craft the Part normally.

Forge: 2757
Gamestages: 2.0.98
TiCo: 2.10.1.87
TinkerStages: 2.0.15

**Comment by MasterEnderman** [comment]
![image](https://user-images.githubusercontent.com/24524662/44404314-eaceec00-a556-11e8-993b-73e2891ee53f.png)
The same thing happens with the Tool Station. It looks like I'm unable to craft it, but if i click where the assembled tool normally will show it crafts it without a problem.

**Comment by Darkhax** [comment]
Sorry for the late response, using the [latest build](https://minecraft.curseforge.com/projects/game-stages/files/2610621) of GameStages should fix this error. Let me know if it works.
